<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InventoryFlow.DataAccess\InventoryFlow.DataAccess.csproj" />
    <ProjectReference Include="..\InventoryFlow.Entities\InventoryFlow.Entities.csproj" />
  </ItemGroup>

</Project>
